// Mock Data
export const HERO_SLIDES = [
  {
    id: 1,
    title: 'Special Pizza Offer',
    subtitle: 'Get 20% Off on All Pizzas',
    description: 'Order now and enjoy our delicious handcrafted pizzas made with fresh ingredients.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=400&fit=crop',
    badge: '🔥 Hot Deal',
    badgeColor: 'red',
    buttonText: 'Order Now',
    discount: '20% OFF',
    rating: 4.8,
    orders: 1245,
    deliveryTime: '25-35 min',
    color: 'red',
  },
  {
    id: 2,
    title: 'Healthy Choice',
    subtitle: 'Fresh Salads & Bowls',
    description: 'Discover our range of healthy and delicious salads made with organic vegetables.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=400&fit=crop',
    badge: '🌿 Healthy',
    badgeColor: 'green',
    buttonText: 'Explore Menu',
    discount: '15% OFF',
    rating: 4.9,
    orders: 876,
    deliveryTime: '20-30 min',
    color: 'green',
  },
  {
    id: 3,
    title: 'Burger Festival',
    subtitle: 'Premium Burgers Collection',
    description: 'Indulge in our gourmet burgers with premium ingredients. From classic to exotic!',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=400&fit=crop',
    badge: '🎉 Festival',
    badgeColor: 'orange',
    buttonText: 'View Burgers',
    discount: 'Buy 1 Get 1',
    rating: 4.7,
    orders: 2341,
    deliveryTime: '30-40 min',
    color: 'orange',
  },
  {
    id: 4,
    title: 'Sushi Special',
    subtitle: 'Authentic Japanese Cuisine',
    description: 'Experience the finest sushi and Japanese dishes prepared by our expert chefs.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&h=400&fit=crop',
    badge: '✨ Premium',
    badgeColor: 'violet',
    buttonText: 'Order Sushi',
    discount: 'Free Delivery',
    rating: 4.9,
    orders: 1567,
    deliveryTime: '35-45 min',
    color: 'violet',
  },
];